"""add entity

Revision ID: 5c8a505259ae
Revises: 
Create Date: 2023-03-24 10:13:08.128722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5c8a505259ae"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deleted_entity",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "deleted_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "deleted_entity_definition",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "deleted_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("entity_uuid", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_name", sa.String(), nullable=False),
        sa.Column("entity_description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "deleted_entity_relationship",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "deleted_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("relationship_type", sa.String(), nullable=False),
        sa.Column("entity_a_uuid", sa.UUID(), nullable=False),
        sa.Column("entity_b_uuid", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "entity",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "entity_definition",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("entity_uuid", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_name", sa.String(), nullable=False),
        sa.Column("entity_description", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_uuid"],
            ["entity.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "entity_relationship",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("relationship_type", sa.String(), nullable=False),
        sa.Column("entity_a_uuid", sa.UUID(), nullable=False),
        sa.Column("entity_b_uuid", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_a_uuid"],
            ["entity.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["entity_b_uuid"],
            ["entity.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entity_relationship")
    op.drop_table("entity_definition")
    op.drop_table("entity")
    op.drop_table("deleted_entity_relationship")
    op.drop_table("deleted_entity_definition")
    op.drop_table("deleted_entity")
    # ### end Alembic commands ###
